[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "wotr"
version = "0.0.1"
dependencies = ["mypy", "black"]

[project.scripts]
wotr = "wotr.main:main"


